<a href="https://colab.research.google.com/github/TanakaSeiju/EU_M_Math-Repository/blob/main/Chap02_Ex_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import scipy.linalg as linalg

matrix = np.array([[1, 2, 3], [1, 3, 2], [3, 1, 2]])

a = linalg.inv(matrix)

eiv_values, eiv_vector = linalg.eig(matrix)

print("逆行列")
print(a)
print("固有値:")
print(eiv_values)
print("固有ベクトル:")
print( eiv_vector)

逆行列
[[-0.33333333  0.08333333  0.41666667]
 [-0.33333333  0.58333333 -0.08333333]
 [ 0.66666667 -0.41666667 -0.08333333]]
固有値:
[ 6.        +0.j -1.41421356+0.j  1.41421356+0.j]
固有ベクトル:
[[-0.57735027 -0.72236645  0.16041816]
 [-0.57735027 -0.14290228 -0.81090869]
 [-0.57735027  0.67658381  0.56275492]]
